### ISSUE TITLE
multi-threading

### ISSUE THREAD

**Issue by rabun788** [unfor19/frigga#6]
seems to get hung up on a single CPU core.

<img width="1125" alt="Screen Shot 2020-08-20 at 1 48 57 PM" src="https://user-images.githubusercontent.com/5399846/90807044-e8413180-e2eb-11ea-8ac9-87226d568917.png">

**Comment by unfor19** [comment]
Just to make sure you're using the latest version, can you try - `pip install -U frigga` ?

**Comment by rabun788** [comment]
```bash
➜  ~ pip3 install -U frigga
Requirement already up-to-date: frigga in /usr/local/lib/python3.8/site-packages (1.0.6)
Requirement already satisfied, skipping upgrade: PyYAML>=5.3.1 in /usr/local/lib/python3.8/site-packages (from frigga) (5.3.1)
Requirement already satisfied, skipping upgrade: Click>=7.1.1 in /usr/local/lib/python3.8/site-packages (from frigga) (7.1.2)
Requirement already satisfied, skipping upgrade: beautifulsoup4>=4.9.1 in /usr/local/lib/python3.8/site-packages (from frigga) (4.9.1)
Requirement already satisfied, skipping upgrade: requests>=2.23.0 in /usr/local/lib/python3.8/site-packages (from frigga) (2.24.0)
Requirement already satisfied, skipping upgrade: soupsieve>1.2 in /usr/local/lib/python3.8/site-packages (from beautifulsoup4>=4.9.1->frigga) (2.0.1)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /usr/local/lib/python3.8/site-packages (from requests>=2.23.0->frigga) (2.9)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in /usr/local/lib/python3.8/site-packages (from requests>=2.23.0->frigga) (3.0.4)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.8/site-packages (from requests>=2.23.0->frigga) (1.25.9)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python3.8/site-packages (from requests>=2.23.0->frigga) (2020.6.20)
```
i just pulled it fresh, so im fairly confident its up to date.
sorry, trying to diagnose, but im really bad at python.

**Comment by unfor19** [comment]
Looks good, let's  try another command - `frigga -h`, any output? Or is it still frozen?

**Comment by rabun788** [comment]
```bash
➜  ~ frigga --help
Usage: frigga [OPTIONS] COMMAND [ARGS]...

  No confirmation prompts

Options:
  -ci, --ci  Use this flag to avoid confirmation prompts
  --help     Show this message and exit.

Commands:
  grafana-list      Provide Grafana UrL and Grafana API Key (Viewer)
                    Returns...

  prometheus-apply
```

**Comment by rabun788** [comment]
Running on my mac it does the same thing, 100% cpu, 1 core.

<img width="1358" alt="Screen Shot 2020-08-20 at 4 16 33 PM" src="https://user-images.githubusercontent.com/5399846/90821208-85a66080-e300-11ea-8bb0-7d58d25369b8.png">

**Comment by unfor19** [comment]
I see you have docker installed, can you try-

```bash
docker run --rm -it unfor19/frigga gl
```

**Comment by rabun788** [comment]
<img width="1059" alt="Screen Shot 2020-08-20 at 7 21 18 PM" src="https://user-images.githubusercontent.com/5399846/90835331-556bbb80-e31a-11ea-851d-be29d0886ce9.png">
```bash
 docker run --rm --net host -it unfor19/frigga gl -gurl http://localhost:3000 -gkey eyJrIjoicTlpSjQx....
```
same thing

**Comment by unfor19** [comment]
I'm ok with the 100% cpu, as long as the memory is slow
 But does it still hang?

Regarding the 100% cpu, you can Google about it, that's a normal behavior. Does it still hang?

**Comment by unfor19** [comment]
@rabun788 were you able to figure it out? I can't seem to reproduce this issue

**Comment by rabun788** [comment]
Not yet.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by unfor19** [comment]
@rabun788 I'm closing this issue for now.

If you have more inputs, feel free to re-open this issue and tag me @unfor19
